name: release

on:
  release:
    types: [published]

jobs:
  x86_64-windows-msvc-cmd:
    strategy:
      fail-fast: false
      matrix:
        build-mode: [debug, release]

    name: x86_64-windows-msvc (cmd/, ${{ matrix.build-mode }} mode)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: clang version
        shell: powershell
        run: |
          clang -v

      - name: Configure and build
        shell: powershell
        working-directory: cmd
        run: |
          xmake config -p windows -a x64 --toolchain=x86_64-windows-msvc-clang -m ${{ matrix.build-mode }}
          xmake build -v

      - name: Run
        shell: powershell
        working-directory: cmd
        run: |
          xmake run pltxt2htm

      - name: Install
        shell: powershell
        working-directory: cmd
        run: |
          xmake install -o auto

      - name: Archive install dir
        shell: powershell
        working-directory: cmd
        run: |
          $dir = Join-Path (Get-Location) "x86_64-windows-msvc-pltxt2htm-cmd-${{ matrix.build-mode }}"
          Compress-Archive -Path $dir -DestinationPath (Join-Path (Split-Path $dir) "$((Get-Item $dir).Name).zip")

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: cmd/x86_64-windows-msvc-pltxt2htm-cmd-${{ matrix.build-mode }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
